---
title: "Slides"
number-sections: true
---

We use HuggingFace pipelines in the following tutorials.

You have several options to start code development:

1. **Colab**: Click on one of the links "💻 Jupyter Notebook" to start a Colab session. 

2. **Local**: Click on one of the links "💻 Jupyter Notebook" below, go to the Colab menu and choose "File" > "Download" > "Download .ipynb"

3. **Cloud Codespace**: Work in a fully configured dev environment in the cloud with a [GitHub Codespace VS Code Browser](https://github.com/kirenz/lab-llm-gradio/blob/main/README.md) environment.

4. **Local VS Code with Codespace**: Use [GitHub Codespaces in your local Visual Studio Code environment](https://docs.github.com/en/codespaces/developing-in-codespaces/using-github-codespaces-in-visual-studio-code).

# Gradio NLP Apps

In this tutorial, you'll create two NLP apps (text summarization and name entitiy recognition) with a Gradio interface:

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/1_nlp_apps.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-llm-gradio/blob/main/code/1_nlp_apps.ipynb)
:::


# Image Captioning App

In this tutorial, you'll create an image captioning app with a Gradio interface:

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/2_image_captioning_app.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-llm-gradio/blob/main/code/2_image_captioning_app.ipynb)
:::


# Image Generation App

In this tutorial, you'll create an image geneartion app with a Gradio interface:

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/3_image_generation_app.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-llm-gradio/blob/main/code/3_image_generation_app.ipynb)
:::

